### ISSUE TITLE
Devtools "render_on_client" running twice causes some problems

### ISSUE THREAD

**Issue by adailey14** [halt-hammerzeit/react-isomorphic-render#12]
In my setup I am doing some things loading 3rd party scripts. When I run in development mode, the code gets mounted twice, and this causes some of the 3rd party scripts to fail. Is there any way to prevent this? Maybe devtools could be mounted separately from the rest of the client application (like in a separate div included in the html)?

(Posted this a second ago under a different github account by accident)

**Comment by halt-hammerzeit** [comment]
Can you describe exactly what is happening and how exactly do plugins fail?

**Comment by halt-hammerzeit** [comment]
And also how do you load your 3rd party scripts

**Comment by adailey14** [comment]
We are doing something like this:

```
import React, { Component } from 'react';

export default class ScriptAttacher extends Component {
  componentDidMount() {
    const script = document.createElement('script');
    script.setAttribute('type', 'text/javascript');
    script.setAttribute('src', 'https://somethirdpartyscript.js');
    this.refs.scriptContainer.appendChild(script);
  }

  shouldComponentUpdate() {
    return false;
  }

  render() {
    return (
      <div>
        <div ref="scriptContainer" />
        <form id="some-id-used-by-3rd-party-script" method="POST"></form>
      </div>
    );
  }
}
```

This loads up the third party script after the form with id is rendered, and it adds a button to the form. 

ShouldComponentUpdate returning false makes sure react will only render it once, otherwise it will remove the button when re-rendering.

When we run in development mode, we end up with the 3rd party script running twice, and adding two buttons to the form. This is triggered by the devtools section of render_on_client mounting everything twice. Every component on the route we are visiting ends up mounting twice.

We could probably find a different way to do this to get it to work, but was surprised by the mounting twice behavior.

**Comment by halt-hammerzeit** [comment]
Well, while the approach you're using is clearly not React way, I can see a workaround for this particular case.
The second render is for `<DevTools/>`.
https://github.com/halt-hammerzeit/react-isomorphic-render/blob/master/source/redux/render.js#L90
It can be omitted (i guess) in case of `DevTools` extension installed in Chrome.
That would force all developers use Chrome.
Will that do for your situation?

Alternatively, you could iterate children of `scriptContainer` to find out if there's any with this `src`.

**Comment by adailey14** [comment]
Yes that would work. I guess it was more that the double mounting was
unexpected than that it posed a real problem. (I spent a while trying to
figure out why everything was mounting twice before finding my way to the
devtools section. I thought it was something else I was doing)

**Comment by halt-hammerzeit** [comment]
In the meantime, I'm gonna release a slight update to the `asynchronous_middleware`.
Here's the summary note:

"[slight possibility of a breaking change] `http` utility now emits `Failure` Redux event with the `error` different from what it was in `4.0.x`: it used to be the raw `Error` javascript object, and now it is `error.data` containing `{ status: 403, message: 'Unauthorized' }` (if `error.data` is not set then it falls back to the original `error` istance). The reasoning behind this change is that the `error` from the `Failure` Redux event payload is immediately stored in Redux state tree in the corresponding reducer, and since Redux state tree should only contain plain (pure) javascript objects, then it makes sence to store only the useful properties there (`error.data`) instead of an instance of an `Error` class which is not a plain (pure) javascript object (and, therefore, is not serializable, which is not a functional programming approach)."

I guess it shouldn't break someone's code so I'm thinking on making this update not a major versioned one.

Do you use `Failure` events in your code, and if you do, how do you store/handle the `error`s in the payload of this event.
Do you only use `.status` and `.message` of these `error`s or are there any other properties involved.

**Comment by halt-hammerzeit** [comment]
I released the new version, try it out.
It shouldn't rerender when DevTools extension is installed
https://github.com/halt-hammerzeit/react-isomorphic-render/commit/853ceb1b16b67f1e3586f2fbed29698a739693de
I can be reached tomorrow.
