### ISSUE TITLE
How to get html <head> to be valid html with multiple child nodes?

### ISSUE THREAD

**Issue by adailey14** [halt-hammerzeit/react-isomorphic-render#14]
I have some code in my web server.js that looks like this:

```js
import webpageServer from 'react-isomorphic-render/page-server';
import common from '../client/react-isomorphic-render';

export default function (parameters) {
  const server = webpageServer({
    html:
    {
      // Will be inserted into server rendered webpage <head/>
      // (this `head()` function is optional and is not required)
      // (its gonna work with or without this `head()` parameter)
      head: (url) => {
        const script = devtools({ ...parameters, entry: 'main' });
        return (
          <div>
            {__DEVELOPMENT__ && (
              <script dangerouslySetInnerHTML={{ __html: script }} />
            )}
            <script src="https://use.fontawesome.com/0d4417303a.js" />
          </div>
        );
      }
    },
  },
  common);
```

I get a complaint that `<div>` is not a valid child of `<head>`. Any idea how to work around that? Maybe the head function could return an array of nodes to be added to `<head>`?

**Comment by peter-mouland** [comment]
git comments don't like arrow-brackets `<` at the moment, what was your error again?

**Comment by halt-hammerzeit** [comment]
@adailey14 If you look here:
https://github.com/halt-hammerzeit/react-isomorphic-render#miscellaneous-webpage-rendering-server-options

You'll notice that it says:
```
    head: (url) => React element or an array of React elements
```

That's one thing.
The other thing is that the `<script/>` tag is populated automatically from `assets` inside `<body/>`.
If you're populating your `<script/>` in head without `async` then you're ["breaking the web"](https://ponyfoo.com/articles/stop-breaking-the-web) because you're putting code before content.

**Comment by adailey14** [comment]
Aha thank you very much, sorry I missed that.
