### ISSUE TITLE
React Router 4.1.1?

### ISSUE THREAD

**Issue by HoraceShmorace** [halt-hammerzeit/react-isomorphic-render#42]
Does this not work with react-router@4.1.1?

**Comment by halt-hammerzeit** [comment]
No

**Comment by halt-hammerzeit** [comment]
An explanations for those who come here:

I would rewrite this project in `react-router@4` and `history@4` but

* `react-router@4` is a very immature library yet, missing a lot of features `react-router@3` had
* I don't trust the authors of `react-router` and I'm positive that they aren't competent enough so I'm gonna wait until the community fixes `react-router@4` enough so that it can be used as a substitute for `react-router@3`
* `react-router-scroll` [doesn't support `react-router@4`](https://github.com/taion/react-router-scroll/issues/52) for the same reasons and since this library uses `react-router-scroll` I'm not gonna rewrite it for `react-router@4` until `react-router-scroll` supports it

**Comment by Tomcombi** [comment]
This package provides the core routing functionality for React Router, but you might not want to install it directly. If you are writing an application that will run in the browser, you should instead install react-router-dom. But i need to Contact to <a href="https://babasupport.org/routers/verizon-routers-customer-service/591"> Version Routers customer service</a> regarding this.

**Comment by catamphetamine** [comment]
Update: migrated the library from `react-router@3` to `found`.
`found` is a better overall architecture.
