### ISSUE TITLE
Exposing superagent request.abort?

### ISSUE THREAD

**Issue by katzoo** [halt-hammerzeit/react-isomorphic-render#46]
Thanks for all hard work you put into webpack comminunity and this platform!

One question regarding [HTTP utility](https://github.com/halt-hammerzeit/react-isomorphic-render/blob/cdb8b303/source/http%20client.js) - I would like to sometimes abort/cancel requests it produces, but in current form superagent's request (or aborting function) is not exposed anywhere.

I thought about doing a simple change [around here](https://github.com/halt-hammerzeit/react-isomorphic-render/blob/cdb8b303/source/http%20client.js#L188) and add a static property eg:

```jsx
const sendRequest = request.send().then
(
  // ....
)

sendRequest.abort = () => {
  if (request.request && typeof request.request.abort === 'function') {
    request.request.abort()
  }
}

return sendRequest;
```

While this would most likely work (together with replacing http client in webpack) for simple cases (chained requests will hide the `abort` reference), I thought it might be useful enough for you to consider adding some way of aborting/cancelling requests to the main project (especially that superagent allows it).

Besides simple/obvious use case I can see this evolving even into a custom middleware that tracks and cancels previous requests of the same type (eg. based on flag in actions).

If you have some other ideas on how to accomplish similar outcome without messing around [http client](https://github.com/halt-hammerzeit/react-isomorphic-render/blob/cdb8b303/source/http%20client.js) then I'm all ears :)

Thanks!

**Comment by halt-hammerzeit** [comment]
I see, so you're suggesting to add an extra `.abort()` method for the `Promise` being returned.
That's a viable solution since `Promise` spec is unlikely to ever use such method name so it can be considered safe.
Still I implemented it the other way.

Your use case isn't clear.
I guess it's some kind of a background refresh task which is supposed to terminate when the user clicks the same "refresh" button once again.
I'm not sure though how're you gonna cancel the previous request in such a scenario.
Storing it in `window`? Not the most elegant solution.
But it has to be stored somewhere.
`State` is supposed to be JSON-only, as far as I understood Redux concept.
So, I guess, `window` would be the way to go.
And where the cancellation would take place.
Maybe inside reducer, but reducers aren't supposed to take any actions at all as per Redux concept.
So, I guess, the cancellation would happen inside the action itself, like 
```js
if (window.______pending_request && the request is still running)
{
  window._______pending_request.abort()
}
```

As for the other possible ways of obtaining the way to call the `.abort()` method it could be done via `options`.

```js
http.post('/', {}, { onRequest: request => window.request = request })
```

That would be more verbose though but it doesn't hack around the Promise object.

Another thing is retrying: if http request retrying is set up then it wouldn't make sense to call `.abort()` on the Promise which has already been superseded by a new one (therefore having no effect).
A better way would be using the already existing `Promise` chain cancellation concept.
http://bluebirdjs.com/docs/api/cancellation.html
I added `http` utility cancellation, I guess it's gonna work, but only for Bluebird users who enabled Promise cancellation.

Even if retrying isn't used I could add `.abort()` method for the Promise itself but it's not being returned from `http` methods: it's being `.then()`ned and therefore a whole another Promise is returned from the method.

So instead I added the `onRequest(request)` parameter to `http` utility method options.

The following works for me:

```js
http.get('/api/example/users', {}, { onRequest: x => x.abort() })
```

See if it works for you

```
npm install react-isomorphic-render@latest
```

**Comment by katzoo** [comment]
Hey, thanks for a quick response!

Sorry, I should have stated this in my previous comment, but my main use case for this feature was autocomplete/search component that sends debounced requests to api every time user input changes. Cancelling 'dispatched' Promise works fine from the user perspective (eg. results from old query aren't saved in redux store), but there is no need to put unnecessary stress on backend (imagine slow connection with a few seconds delay).

> A better way would be using the already existing Promise chain cancellation concept.
http://bluebirdjs.com/docs/api/cancellation.html
I added http utility cancellation, I guess it's gonna work, but only for Bluebird users who enabled Promise cancellation.

Thanks a lot for this, my project has Bluebird configured, so it's a great fit for the original use case, also it's probably the cleanest approach. I haven't tested your changes yet, but I'm confident they completely cover my issue.

Instead of storing them somewhere on global object, I'd rather go for a simple middleware similar to one below (haven't run/tested this, but assumes Bluebird cancellation is available):
```jsx
const cancelPreviousMiddleware = store => {
  const toCancel = new Map();

  return next => action => {
    const result = next(action);

    if (check if on client && action.cancelPrevious) {
      const [type] = action.events;

      if (toCancel.get(type)) {
        toCancel.get(type).cancel();
      }

      if (result.promise && typeof result.promise.cancel === 'function') {
        toCancel.set(type, result.promise);

        result.promise.finally(() => { toCancel.delete(type); }
      }
    }

    return result;
  };
};
```

and then dispatching again action of the same type should do the trick:
```jsx
function asyncAction() {
  return {
    promise: html => html.get(...),
    events: [....],
    cancelPrevious: true,
  }
}
```

Initially I thought  that somehow exposing superagent's `abort` would be enough and allow people without Bluebird to cancel requests when needed, but now with both additions (`onCancel` and `onRequest`) this is still possible, by having the middleware extend `action.promise` options with `onRequest` that stores superagent request and abort's it when it's called again.

Thanks once again!

**Comment by halt-hammerzeit** [comment]
Ah, now I see what you mean.
I guess that's a generic enough case to make it part of the library.
Even though I find the "2 seconds delay before it even hits the server" case extremely unlikely.
I removed `onRequest` option and added `cancelPrevious: true` flag to asynchronous actions.
(see the updated readme for details)
And also watch out for `.finally` because it's only for `bluebird` and would break the default Promise implementation.
